### ISSUE TITLE
Incorrect Parse version

### ISSUE THREAD

**Issue by nelsyeung** [rabidaudio/bower-parse#10]
Currently this repo says v1.6.12, but the Parse library inside is v1.6.13. 
i.e., bower install -D parse will show 1.6.12 in bower.json, but the actual parse library is 1.6.13.

**Comment by rabidaudio** [comment]
Thanks for pointing this out. This seems to actually an issue with [the upstream repo](https://github.com/ParsePlatform/Parse-SDK-JS), as checking out npm version 1.6.12 actually contains 1.6.13. Anyway I compiled version 1.6.12 manually and did a force retag of the commit, so you may need to uninstall and reinstall to get the proper 1.6.12.
