### ISSUE TITLE
v1.6.0 getAuthType is not a function

### ISSUE THREAD

**Issue by limulidae** [rabidaudio/bower-parse#5]
just update to v1.6.0 and get this fail.
rollback to v.1.5.0 is working.

**Comment by rabidaudio** [comment]
Version `1.6.0` contains a number of breaking changes. See [the Changelog](https://parse.com/docs/downloads). You probably want to stick with `1.5.0` if your app is Backbone based

**Comment by limulidae** [comment]
sorry I dont understand 'backbone based'.
I am just following https://www.parse.com/docs/js/guide#users-facebook-users,
do i need any more change besides https://www.parse.com/docs/js/guide#users-facebook-users?

**Comment by limulidae** [comment]
one more thing to say, I am using Ionic, is this 'backbone based'?

**Comment by rabidaudio** [comment]
[Backbone.js](backbonejs.org) is a front-end javascript framework. I think Ionic is built on Angular though. In any case, it isn't important. 

I'm not affiliated with Parse, I just post the code to Bower, so I can't really offer support about how to use the library. But my recommendation is that if `1.5.0` is working, I'd stick with it.
